services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - tuna

  tuna:
    image: yuccastream/tuna:latest
    container_name: tuna
    command: tuna http 8080
    volumes:
      - ./tuna-config:/root/.config/tuna
    ports:
      - "8080:8080"
